### ISSUE TITLE
Add compatibility constraints for Frama-C versions

### ISSUE THREAD

**Issue by maroneze** [Stevendeo/Pilat#1]
The latest Frama-C release (Chlorine) is incompatible with `pilat` 1.1. I added a constraint in the opam file, but it is not enough: opam is still able to find an old release (2014) and tries to install it, and them `pilat`, but fails miserably.

I would recommend checking the oldest release of Frama-C that should be compatible with pilat and blacklisting those older than that, to avoid opam from being able to find exotic package combinations.

Otherwise, you might consider adding a strong `depends` constraint with the exact Frama-C version that is known to be compatible with your plug-in. It's a bit excessive, but at least prevents your users from getting installation errors. You can then whitelist new releases as they come, if they remain compatible.

**Comment by Stevendeo** [comment]
Thank you for the feedback. I think I will go for your second idea for now so that I am sure that people who wants to use pilat can do it easily. 
As my current version of pilat currently works on Chlorine, I will set the constraint on this when it is available on Opam.

**Comment by maroneze** [comment]
Thanks! If you can, please update both the constraints on the old version (1.1, to avoid build fails in opam's CI) and in the new one.

**Comment by Stevendeo** [comment]
Oh ok I will do it. Do you think opam checks dependencies of every old versions of packages ?

**Comment by maroneze** [comment]
It usually does, I did some backporting of constraints on older releases of Frama-C some time ago because of that. Unfortunately the Opam Weather Service no longer seems to work and I don't recall if there is another place where we can see all builds, but there used to be a huge table with several versions of packages tested, including older ones.
